/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kevin;

/**
 *
 * @author Admin
 */
public class Principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());

    /**
     * Creates new form Pirncipal
     */
    public Principal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnConexion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabla = new javax.swing.JTable();
        jTxtNombreAutor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTxtidlibro = new javax.swing.JTextField();
        jTxttitulo = new javax.swing.JTextField();
        jTxtanio = new javax.swing.JTextField();
        jTxtid_autor = new javax.swing.JTextField();
        jBtnAceptarAutor = new javax.swing.JButton();
        jBtnVerlibros = new javax.swing.JButton();
        jBtnVerAutores = new javax.swing.JButton();
        jBtnAceptarLibro = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTxtid_autorN = new javax.swing.JTextField();
        jTxtNacionalidad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtnConexion.setText("Conexion");
        jBtnConexion.addActionListener(this::jBtnConexionActionPerformed);

        jTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "IdAutor", "Nombre", "IdLibro", "Titulo", "Anio"
            }
        ));
        jScrollPane1.setViewportView(jTabla);

        jTxtNombreAutor.addActionListener(this::jTxtNombreAutorActionPerformed);

        jLabel1.setText("Ingresar  autor");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Ingresar  libro:");

        jLabel4.setText("id libro:");

        jLabel5.setText("titulo");

        jLabel6.setText("anio");

        jLabel7.setText("id_autor");

        jTxtidlibro.addActionListener(this::jTxtidlibroActionPerformed);

        jBtnAceptarAutor.setText("Aceptar");
        jBtnAceptarAutor.addActionListener(this::jBtnAceptarAutorActionPerformed);

        jBtnVerlibros.setText("Ver libros");
        jBtnVerlibros.addActionListener(this::jBtnVerlibrosActionPerformed);

        jBtnVerAutores.setText("Ver autores");
        jBtnVerAutores.addActionListener(this::jBtnVerAutoresActionPerformed);

        jBtnAceptarLibro.setText("Aceptar");
        jBtnAceptarLibro.addActionListener(this::jBtnAceptarLibroActionPerformed);

        jLabel8.setText("id_autor");

        jLabel9.setText("Nacionalidad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBtnConexion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(158, 158, 158)
                                .addComponent(jLabel3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtnAceptarAutor)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel9)))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtid_autorN, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtNombreAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtidlibro, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTxtid_autor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTxttitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtanio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addComponent(jBtnAceptarLibro)))))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBtnVerlibros)
                .addGap(50, 50, 50)
                .addComponent(jBtnVerAutores)
                .addGap(169, 169, 169))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnConexion)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtNombreAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jTxtidlibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTxttitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jTxtid_autorN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jTxtanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTxtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBtnAceptarLibro)
                        .addGap(25, 25, 25)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTxtid_autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnAceptarAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnVerAutores)
                    .addComponent(jBtnVerlibros))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConexionActionPerformed
      Conexion cn= new Conexion();
        cn.conectar();
    }//GEN-LAST:event_jBtnConexionActionPerformed

    private void jTxtNombreAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNombreAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNombreAutorActionPerformed

    private void jTxtidlibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtidlibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtidlibroActionPerformed

    private void jBtnVerAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVerAutoresActionPerformed
        // TODO add your handling code here:
        AutorDAO autor = new AutorDAO();
jTabla.setModel(autor.mostrarAutores());
    }//GEN-LAST:event_jBtnVerAutoresActionPerformed

    private void jBtnVerlibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVerlibrosActionPerformed
       LibroDAO libro = new LibroDAO();
jTabla.setModel(libro.mostrarLibros());
    }//GEN-LAST:event_jBtnVerlibrosActionPerformed

    private void jBtnAceptarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAceptarAutorActionPerformed
         jTabla.setModel(new AutorDAO().aceptarAutor(
            jTxtid_autorN.getText(),
            jTxtNombreAutor.getText(),
            jTxtNacionalidad.getText()
    ));
    }//GEN-LAST:event_jBtnAceptarAutorActionPerformed

    private void jBtnAceptarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAceptarLibroActionPerformed
        LibroDAO dao = new LibroDAO();
String mensaje = dao.ingresarLibro(
        jTxtidlibro.getText(),
        jTxttitulo.getText(),
        jTxtanio.getText(),
        jTxtid_autor.getText()
);
javax.swing.JOptionPane.showMessageDialog(this, mensaje);

    jTabla.setModel(dao.mostrarLibros());

    }//GEN-LAST:event_jBtnAceptarLibroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAceptarAutor;
    private javax.swing.JButton jBtnAceptarLibro;
    private javax.swing.JButton jBtnConexion;
    private javax.swing.JButton jBtnVerAutores;
    private javax.swing.JButton jBtnVerlibros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabla;
    private javax.swing.JTextField jTxtNacionalidad;
    private javax.swing.JTextField jTxtNombreAutor;
    private javax.swing.JTextField jTxtanio;
    private javax.swing.JTextField jTxtid_autor;
    private javax.swing.JTextField jTxtid_autorN;
    private javax.swing.JTextField jTxtidlibro;
    private javax.swing.JTextField jTxttitulo;
    // End of variables declaration//GEN-END:variables
}
